### ISSUE TITLE
asa_config: Default settings configuration may not be idempotent

### ISSUE THREAD

**Issue by robertegithub** [ansible-collections/cisco.asa#101]
##### SUMMARY

When a setting is at the default already, and the asa_config module is provided that same configuration in the "lines" parameter, it appears to implement the configuration even though it exists already, with the "defaults" parameter set to "yes".

Collection             Version
---------------------- -------
ansible.netcommon      2.0.0  
ansible.utils          2.0.1  
cisco.asa              2.0.0  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.asa.asa_config

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = None
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/xxx/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = /Users/xxx/Library/Python/3.8/bin/ansible
  python version = 3.8.2 (default, Dec 21 2020, 15:06:04) [Clang 12.0.0 (clang-1200.0.32.29)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Targets tested on:
Cisco Adaptive Security Appliance Software Version 9.12(4)4 
Cisco Adaptive Security Appliance Software Version 9.8(4)29 

Ansible engine host is MacOS 11.2.3

##### STEPS TO REPRODUCE

Configure asa_config module task with "lines" including a default configuration (password-policy lifetime 0, for example)
Use parameter "defaults: yes" in order to force module to get "show run all" data for configuration comparison
If the configuration already exists, the module appears to implement it anyway

```yaml
- name: implement the change on the device
      cisco.asa.asa_config:
        lines:
          - password-policy lifetime 0
        save: yes
        defaults: yes
```

##### EXPECTED RESULTS

Command is not implemented / "updates" is empty

##### ACTUAL RESULTS

Command appears to be implemented / "updates" is populated 
Monitoring with "terminal monitor" also confirms the command is implemented:
%ASA-5-111007: Begin configuration: x.x.x.x reading from terminal
%ASA-5-111008: User 'enable_15' executed the 'configure terminal' command.
%ASA-5-111010: User 'enable_15', running 'CLI' from IP x.x.x.x, executed 'configure terminal'
%ASA-5-111008: User 'enable_15' executed the 'password-policy lifetime 0' command.
%ASA-5-111010: User 'enable_15', running 'CLI' from IP x.x.x.x, executed 'password-policy lifetime 0'
%ASA-5-111005: x.x.x.x end configuration: OK

```paste below
changed: [x.x.x.x] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "after": null,
            "authorize": null,
            "backup": false,
            "backup_options": null,
            "before": null,
            "config": null,
            "context": null,
            "defaults": true,
            "lines": [
                "password-policy lifetime 0"
            ],
            "match": "line",
            "parents": null,
            "passwords": null,
            "provider": null,
            "replace": "line",
            "save": true,
            "src": null
        }
    },
    "updates": [
        "password-policy lifetime 0"
    ]
}
```

**Comment by robertegithub** [comment]
Minor additional information:

I increased the logging level on the test ASA to capture "show" commands and monitored the playbook. I have two tasks where the asa_config module is configured to use the "defaults: yes" parameter (as seen in the example above). 

There were never any "show running-config all" commands issued:

%ASA-7-111009: User 'enable_15' executed cmd: show running-config
%ASA-7-111009: User 'enable_15' executed cmd: show running-config
%ASA-7-111009: User 'enable_15' executed cmd: show running-config
%ASA-7-111009: User 'enable_15' executed cmd: show running-config

**Comment by justjais** [comment]
@robertegithub Thanks for logging the issue. Yes, the default configuration settings are not taken to account for checking the idempotency comparison and it checks with `sh running-config` and not with `sh running-config all`.

Currently, we're don’t have any plans for implementing the same anytime soon. We'll update the collections if and when the logic will be implemented.
