### ISSUE TITLE
Enable Cisco ASA Botnet Traffic Filter via dynamic/static DB configuration 

### ISSUE THREAD

**Issue by justjais** [ansible-collections/cisco.asa#115]
##### SUMMARY

Enable Cisco ASA Botnet Traffic Filter via dynamic/static DB configuration.

Malware that attempts network activity such as sending private data (passwords, credit card numbers, keystrokes, or proprietary data) can be detected by the Botnet Traffic Filter when the malware starts a connection to a known bad IP address. The Botnet Traffic Filter checks incoming and outgoing connections against a dynamic/static database of known bad domain names and IP addresses (the blacklist), and then logs or blocks any suspicious activity. For more information around the feature, plz ref: [Cisco Botnet traffic filter guide](https://www.cisco.com/c/en/us/td/docs/security/asa/special/botnet/guide/asa-botnet.html)

If Ansible has the ASA `dynamic_filter` module to configure, this entire process of configuring and adding the address to static DB or enabling dynamic DB can be automated, and the process can then be integrated with Ansible security SIEM offerings and can easily be converted to solve and automate the task of incident response use case using Cisco ASA.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

cisco.asa

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by justjais** [comment]
@sebrower, @busseax, @robertegithub, @omegafoo, @FeoZ, @devon-mar, @sagarphadatare44 Hope you all doing well.I've opened this issue request around ASA botnet feature, so wanted to check with people like

**Comment by robertegithub** [comment]
Great idea - the more features that can be automated the better.

**Comment by justjais** [comment]
@robertegithub cool, thx for your swift response. Can you plz let me know of few insights about the particular feature:
- Have you used the feature before?
- How do you use the feature, are you combining this with any other feature to solve a particular use case?
- Do you want any specific use case to target with automating the botnet traffic filter use-case?

This is also, intended for all whom I've tagged in my earlier comment, community help and encouragement are absolutely necessary for us to start working on new features.

**Comment by busseax** [comment]
@justjais Thanks for the heads up. We are not using this feature and since we are only using our ASAs as VPN endpoints we probably won't use it in the near future.

**Comment by devon-mar** [comment]
Like what @busseax said, I'm only using ASAs as VPN headends. Most people running a SIEM will probably be running NGFWs at this point.
I think it would be more worthwhile to work on other modules like `asa_static_routes`, or `asa_interfaces`, modules for ASA features that are more commonly used.

**Comment by justjais** [comment]
@busseax @devon-mar thanks for your feedback, much appreciated. This definitely helps while committing for a new features.

And @devon-mar, `asa_static_routes` is under my radar, I'll soon update the progress on it, though I am not very sure about the `interfaces` module.

**Comment by justjais** [comment]
Closing the feature issue as the use-case doesn’t seem to be worth implementing as this feature is taken care of mostly by NGFW.

If still anyone strongly feels that botnet traffic filter is worth automating, please go ahead and re-open the issue with relevant reasoning.
