### ISSUE TITLE
asa_ogs: Error when parsing object-group protocol containing an integer value

### ISSUE THREAD

**Issue by robertegithub** [ansible-collections/cisco.asa#116]
##### SUMMARY

When a "protocol" object-group contains a member like:
protocol-object 16
the asa_ogs task fails with a fatal error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

asa_ogs

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.10.3
  config file = None
  configured module search path = ['path/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = path/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = path/Library/Python/3.8/bin/ansible-playbook
  python version = 3.8.2 (default, Apr  8 2021, 23:19:18) [Clang 12.0.5 (clang-1205.0.22.9)]
```

##### CONFIGURATION

```paste below
[empty]
```

##### OS / ENVIRONMENT

MacOS using python 3.8, but also tested from Ansible Tower using python 2.7
# path/.ansible/collections/ansible_collections
Collection             Version
---------------------- -------
ansible.netcommon      2.1.0  
ansible.utils          2.2.0  
cisco.asa              2.0.2  
paloaltonetworks.panos 2.5.0  

##### STEPS TO REPRODUCE

Configure a protocol object-group similar to:
test_asa_fw_01/admin# show run object-group protocol 
object-group protocol proto1
 protocol-object tcp
 protocol-object 16
 protocol-object udp
test_asa_fw_01/admin#

```yaml
tasks:
    - name: Get network object groups only
      cisco.asa.asa_ogs:
        config:
        state: gathered
```

##### EXPECTED RESULTS

Expectation is the groups will be parsed without an error. Integers between 0 and 255 are valid (test firewall version 9.12(4)18):

test_asa_fw_01/admin(config-protocol-object-group)# protocol-object ?

protocol-object-group mode commands/options:
  <0-255>  Enter protocol number (0 - 255)
  ah       
  eigrp    
  esp      
  gre      
  icmp     
  icmp6    
  igmp     
  igrp     
  ip       
  ipinip   
  ipsec    
  nos      
  ospf     
  pcp      
  pim      
  pptp     
  sctp     
  snp      
  tcp      
  udp      
test_asa_fw_01/admin(config-protocol-object-group)#

##### ACTUAL RESULTS

fatal error. Note also that the "state" provided in the task is "gathered", but the task output says, "merged"

```paste below
...
    "invocation": {
        "module_args": {
            "running_config": null,
            "state": "merged",
            "config": [
		...
            ]
        }
    },
    "changed": false,
    "msg": "value of protocol must be one or more of: ah, eigrp, esp, gre, icmp, icmp6, igmp, igrp, ip, ipinip, ipsec, nos, ospf, pcp, pim, pptp, sctp, snp, tcp, udp. Got no match for: 16 found in config -> object_groups -> protocol_object"
}
```

**Comment by justjais** [comment]
@robertegithub Thanks for raising the issue, and I've raised the PR to fix the observed issue, and once merged it'll be queued for June'21 release.
