### ISSUE TITLE
asa_ogs: "Unsupported parameters" in network_object

### ISSUE THREAD

**Issue by FeoZ** [ansible-collections/cisco.asa#99]
#### SUMMARY

Module asa_ogs show unexpected behavior while using network_object parameter

#### ISSUE TYPE

* Bug Report

#### COMPONENT NAME

* cisco.asa.asa_ogs

#### ANSIBLE VERSION

    ansible 2.9.9
    python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]

#### CONFIGURATION

    command_timeout = 60
    host_key_checking = False

#### OS / ENVIRONMENT

Tested against ASA 5525-X - Version: 9.14(2)8, 
Ansible running on Ubuntu 20.04.2 LTS

#### STEPS TO REPRODUCE

Run the asa_ogs module with the "network_object" parameter in a task. 
Following task as an example - found in the documentation (https://github.com/ansible-collections/cisco.asa/blob/main/docs/cisco.asa.asa_ogs_module.rst)

    - name: "Merge module attributes of given object-group"
      cisco.asa.asa_ogs:
        config:
        - object_type: network
          object_groups:
            - name: test_og_network
              description: test_og_network
              network_object:
                host:
                  - 192.0.2.1
                  - 192.0.2.2
                address:
                  - 192.0.2.0 255.255.255.0
                  - 198.51.100.0 255.255.255.0

#### EXPECTED RESULTS

Module creates network object as specified. 

#### ACTUAL RESULTS

Module raises the following error at playbook launch: 
    
    "msg": "Unsupported parameters for (basic.py) module: object found in config -> object_groups -> network_object. Supported parameters include: address, host, ipv6_address"

**Comment by stephenpaynter** [comment]
Having same issue. Any updates on this open issue

**Comment by benjdudas** [comment]
This issue seems to be triggered by having a object-group mapped with a network-object already configured on the ASA. 

ASA config prior to running the task:
```
object network TEST
 host 2.2.2.2 
 description asa_ogs test
object-group network ANSIBLE_TEST
 network-object object TEST
```

Result:
```
fatal: [X.X.X.X]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "config": [
                {
                    "object_groups": [
                        {
                            "description": null, 
                            "icmp_type": null, 
                            "name": "ANSIBLE_TEST", 
                            "network_object": {
                                "object": "TEST"
                            }, 
                            "protocol_object": null, 
                            "security_group": null, 
                            "service_object": null, 
                            "user_object": null
                        }
                    ], 
                    "object_type": "network"
                }
            ], 
            "running_config": null, 
            "state": "merged"
        }
    }, 
    "msg": "Unsupported parameters for (basic.py) module: object found in config -> object_groups -> network_object. Supported parameters include: address, host, ipv6_address"
```

**Comment by justjais** [comment]
@FeoZ @stephenpaynter Thanks for logging the issue, I've raised PR #103 to fix the issue you're facing. Can you please verify if the fix works as expected.
Once merged, it'll be queued for April release.

**Comment by stephenpaynter** [comment]
Please advise how to verify this fix

**Comment by stephenpaynter** [comment]
Has this been merged for pull via collections yet?

**Comment by justjais** [comment]
@stephenpaynter it'll be merged today and available with `devel` version over the galaxy for testing, once out I'll revert back.

**Comment by justjais** [comment]
@stephenpaynter PR with the fix is merged, to verify the fix you can clone the repo and test the respective bug scenario.

**Comment by justjais** [comment]
@stephenpaynter Latest 2.0.1 ASA collection with the issue fix is available over galaxy now: https://galaxy.ansible.com/cisco/asa
